#expose server port for REST
server:
  port: 4001

#expose server port for GRPC
grpc:
  server:
    port: 9001

spring:
  application:
    name: billing-service
  #kafka
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
