### Create a new patient entity (without gateway, testing)
POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "NEW PATIENT NAME",
  "email": "new_patient@example.com",
  "address": "123 Main street",
  "dateOfBirth": "1993-10-08",
  "registeredDate": "2025-09-26"
}


###