### Create a new patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe_CB1",
  "email": "kafka_test_cb1@example.com",
  "address": "123 Main street",
  "dateOfBirth": "1993-10-08",
  "registeredDate": "2025-09-26"
}


###