server:
  port: 4000

spring:
  application:
    name: patient-service
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    username: ${SPRING_DATASOURCE_USERNAME:admin_user}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://patient-service-db:5432/db}
  jpa:
    hibernate:
      ddl-auto: update #for dev.
  sql:
    init:
      mode: always #classpath:data.sql

  #kafka
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

# UNCOMMENT TO USE IN-MEMORY DATABASE OUTSIDE OF DOCKER
#   #h2 - in-memory database (development mode: test)
#  h2:
#    console:
#      path: /h2-console #anytime we start the application that has an H2 in-memory database
#                        # endpoint to see
#  # datasource: setup DB connection (H2 - development mode: test)
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: admin
#    password: test
#  # jpa: configures ORM - hibernate that uses DB connection
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect # be selected by default
#    hibernate:
#      ddl-auto: update #development mode: update entity against table database.
#  # sql: looks for data.sql on the classpath or under 'resources/', Run scripts every time
#  sql:
#    init:
#      mode: always  #development mode.

logging:
  level:
    root: info # all INFO - WARN - ERROR messages be logged to the terminal.

#Resilience4j.CircuitBreaker
resilience4j:
  circuitbreaker:
    instances:
      billingService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      billingRetry:
        maxAttempts: 2
        waitDuration: 500ms

#Observability, Metric
#actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,cache
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true