server:
  port: 4006

spring:
  application:
    name: appointment-service
  #Datasource ( relate to connection to Postgresql)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://appointment-service-db:5432/db}
    username: ${SPRING_DATASOURCE_USERNAME:admin_user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  #jpa (relate to ORM layer, Hibernate)
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
  #sql (init sql)
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:always}
  #kafka
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer